### ISSUE TITLE
No Content? 

### ISSUE THREAD

**Issue by OsakiTsukiko** [serb2331/FreeCell#1]
05ce9d3b6f9d8c92e97f17ae56024951045a1b59

![image](https://user-images.githubusercontent.com/104794884/205465790-69b32fdc-e05a-452d-be00-2e5380776d3c.png)

**Comment by serb2331** [comment]
more like 100 lines

**Comment by OsakiTsukiko** [comment]
![image](https://user-images.githubusercontent.com/104794884/205466168-457278bb-37f9-4b21-ac3e-9a182b14c128.png)
