### ISSUE TITLE
Bruh, ur builds are broken

### ISSUE THREAD

**Issue by OsakiTsukiko** [serb2331/FreeCell#3]
Esteemed Sir.

I am here to alert you to a very urgent problem found in your project!
As it would appear, your builds are failing. This is not an issue of your doing, as your code is entirely satisfactory. This problem stands from the lack of what Godot refers to as "export presets". Thus, I urgently advise you to add said "export presets" for what you have defined as "windows" and "linux" in your workflow file.

Thus I conclude my letter of Issue to you, I hope you can resolve this matter in little time! May the Gods bless you!

**Comment by serb2331** [comment]
Thank you for the information sir, good day.
